image: nberlette/gitpod-enhanced

tasks:
  - name: "init"
    openMode: split-left
    init: |
      # ensure we have pnpm installed
      which pnpm > /dev/null 2>&1 || curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm 2>/dev/null ;
      # add global packages
      pnpm add -g vercel turbo degit bundt typescript tsm prettier eslint svglint svgo 2>/dev/null;
      # install local dependencies
      pnpm install 2>/dev/null;
      # signal other terminal it is ok to proceed
      gp sync-done listo;
    command: pnpm test --if-present 2>/dev/null 
    
  - name: "lint"
    openMode: split-right
    init: gp sync-await listo
    command: pnpm lint --if-present

ports:
  - port: "3000-5000"
    onOpen: notify

gitConfig:
  commit.gpgsign: "true"
  tag.gpgsign: "true"
  credential.helper: "/usr/bin/gp credential-helper"

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addLabel: true
    addBadge: true
    addCheck: true

vscode:
  extensions:
    - github.copilot-nightly
    - eamodio.gitlens
    - vsls-contrib.gistfs
    - github.vscode-codeql
    - peterhdd.github-folder
    - cschleiden.vscode-github-actions
    - esbenp.prettier-vscode
    - editorconfig.editorconfig
    - jock.svg
    - redhat.vscode-yaml
    - gamunu.vscode-yarn
    - jacano.vscode-pnpm
    - eg2.vscode-npm-script
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - voorjaar.windicss-intellisense
    - antfu.unocss
    - antfu.vite
    - davidanson.vscode-markdownlint
    - darkriszty.markdown-table-prettify
